---
abstract: 'Character n-gram tokenizer for Search::Fulltext'
author:
  - 'Koichi SATOH <sekia@cpan.org>'
build_requires:
  Search::Fulltext: 0
  Test::More: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Search-Fulltext-Tokenizer-Ngram
requires:
  Carp: 0
  Scalar::Util: 0
  parent: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/sekia/Search-Fulltext-Tokenizer-Ngram/issues
  repository: git://github.com/sekia/Search-Fulltext-Tokenizer-Ngram.git
version: 0.01
